pub mod buffer;
pub mod command_pool;
pub mod descriptorset;
pub mod device;
pub mod enums;
pub mod framebuffer;
pub mod image;
pub mod instance;
pub mod macros;
pub mod physical_device;
pub mod pipeline;
pub mod queue_family;
pub mod render_pass;
pub mod shader_utils;
pub mod surface;
pub mod swapchain;
pub mod sync;
pub mod utils;

pub use glam;
pub(crate) type RendererError = Box<dyn std::error::Error>;
pub type RendererResult<T> = Result<T, RendererError>;
