[package]
edition = "2021"
name = "sample"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkan_renderer = {path = "../vulkan_renderer"}
winit = "0.26.1"
